use serde::{Deserialize, Serialize};

/// Request payload sent by the client to initialize a new attestation session.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct InitRequest {
    /// Hex-encoded 32-byte Ed25519 public verifying key generated by the client.
    pub public_key: String,
}

/// Response payload returned by the server upon successful session initialization.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InitResponse {
    /// The unique hex-encoded session identifier.
    pub session_id: String,
    /// The initial server-issued salt to be mixed in the first heartbeat's hash.
    pub salt: String,
    /// Base64-encoded initial VM program for client stack execution.
    pub opcodes_b64: String,
    /// The computed initial hash of the attestation chain.
    pub initial_hash: String,
    /// Timestamp in milliseconds indicating when the session expires.
    pub expires_at: u64,
    /// Minimum time in milliseconds allowed between subsequent heartbeats.
    pub heartbeat_min_interval_ms: u64,
    /// Maximum time in milliseconds allowed between subsequent heartbeats.
    pub heartbeat_max_interval_ms: u64,
    /// Size of the synthetic gene byte buffer.
    pub gene_size: u32,
    /// The current mutation step index (starts at 1).
    pub mutation_step: u64,
    /// Base64-encoded initial gene mutation program.
    pub mutation_order_b64: String,
    /// The number of mutation rounds configured on the server.
    pub mutation_rounds: u8,
}

/// Heartbeat request payload submitted periodically by the client to prove session continuity.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct HeartbeatRequest {
    /// The session identifier.
    pub session_id: String,
    /// The expected hash from the previous heartbeat/initialization step.
    pub prev_hash: String,
    /// The client's current system timestamp in milliseconds.
    pub timestamp: u64,
    /// The collected client entropy data (such as mouse events).
    pub entropy_data: EntropyData,
    /// The final execution state of the client's VM stack program.
    pub stack_state: StackState,
    /// The client's browser hardware and layout fingerprint.
    pub fingerprint: Fingerprint,
    /// The mutation step index corresponding to the pending mutation.
    pub mutation_step: u64,
    /// Hex-encoded commitment of the mutated gene state.
    pub gene_commitment: String,
    /// Ed25519 signature of the canonical JSON-serialized payload.
    pub signature: String,
}

/// Response payload returned by the server for heartbeat submissions.
///
/// In case of silent rejection, all fields except `status` are omitted.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HeartbeatResponse {
    /// Attestation status, typically "ok" even on silent failures.
    pub status: String,
    /// The next server-issued salt for hash chain progression.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_salt: Option<String>,
    /// The next expected mutation step index.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_mutation_step: Option<u64>,
    /// Base64-encoded next mutation program for client gene progression.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_mutation_order_b64: Option<String>,
}

/// Client browser fingerprint metadata used for basic sanity checks.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Fingerprint {
    /// Aspect ratio of the client screen.
    #[serde(rename = "aspectRatio")]
    pub aspect_ratio: String,
    /// Device pixel ratio of the screen.
    #[serde(rename = "devicePixelRatio")]
    pub device_pixel_ratio: String,
    /// Number of logical processor cores available.
    #[serde(rename = "hardwareConcurrency")]
    pub hardware_concurrency: u32,
}

/// Wrapper for browser-side entropy collection.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct EntropyData {
    /// A chronological list of mouse movement events.
    pub events: Vec<MouseEvent>,
}

/// Information about a single mouse movement interaction.
#[derive(Deserialize, Serialize, Clone, Debug)]
pub struct MouseEvent {
    /// Absolute horizontal coordinate of the cursor.
    pub x: f64,
    /// Absolute vertical coordinate of the cursor.
    pub y: f64,
    /// Relative timestamp in milliseconds of the event occurrence.
    #[serde(rename = "t")]
    pub timestamp_ms: f64,
}

/// The state of the VM stack machine after executing a program.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StackState {
    /// The elements remaining on the stack.
    pub stack: Vec<u32>,
    /// The final instruction pointer location at program completion or termination.
    pub ip: u16,
}

